glorifiedKing/bustravel

- resources/views/backend/operators/index.blade.php
- src/Http/Controllers/OperatorsController.php
finished operators controller ready for review
> operators controller

- database/factories/BusFactory.php
- database/migrations/2019_11_06_081630_create_buses_table.php
- resources/views/backend/buses/create.blade.php
- resources/views/backend/buses/edit.blade.php
- resources/views/backend/buses/index.blade.php
- routes/web.php
- src/Bus.php
- src/Http/Controllers/BusesController.php
- tests/Feature/BusesTest.php
> Feature Buses

- database/factories/RouteFactory.php
- database/migrations/2019_11_09_081630_create_routes_table.php
- resources/views/backend/buses/create.blade.php
- resources/views/backend/buses/edit.blade.php
- resources/views/backend/buses/index.blade.php
- resources/views/backend/operators/create.blade.php
- resources/views/backend/operators/edit.blade.php
- resources/views/backend/routes/create.blade.php
- resources/views/backend/routes/edit.blade.php
- resources/views/backend/routes/index.blade.php
- routes/web.php
- src/Bus.php
- src/BusTravelBaseServiceProvider.php
- src/Http/Controllers/BusesController.php
- src/Http/Controllers/OperatorsController.php
- src/Http/Controllers/RouteController.php
- src/Route.php
- tests/Feature/BusesTest.php
- tests/Feature/OperatorsTest.php
- tests/Feature/RoutesTest.php
> feature-routes

- database/factories/DriverFactory.php
- database/factories/RouteFactory.php
- database/migrations/2019_11_10_081630_create_drivers_table.php
- resources/views/backend/drivers/create.blade.php
- resources/views/backend/drivers/edit.blade.php
- resources/views/backend/drivers/index.blade.php
- routes/web.php
- src/Driver.php
- src/Http/Controllers/DriversController.php
- src/Http/Controllers/OperatorsController.php
- src/Http/Controllers/RouteController.php
- src/Route.php
- tests/Feature/DriversTest.php
- tests/Feature/RoutesTest.php
> Feature Drivers

- database/factories/RoutesDepartureTimeFactory.php
- database/migrations/2019_11_11_081630_create_routes_departure_times_table.php
- resources/views/backend/routes/create.blade.php
- resources/views/backend/routes/edit.blade.php
- resources/views/backend/routes_departures/create.blade.php
- resources/views/backend/routes_departures/edit.blade.php
- resources/views/backend/routes_departures/index.blade.php
- routes/web.php
- src/BusTravelBaseServiceProvider.php
- src/Http/Controllers/RoutesDepartureTimesController.php
- src/RoutesDepartureTime.php
- tests/Feature/RoutesDepartureTimesTest.php
Feature Routes Departure Times
> feature Routes Departure Times

- database/factories/BookingCustomFeildFactory.php
- database/factories/BookingFactory.php
- database/factories/BookingsFieldFactory.php
- database/migrations/2019_11_12_081630_create_booking_custom_fields_table.php
- database/migrations/2019_11_12_091630_create_bookings_table.php
- database/migrations/2019_11_12_091730_create_booking_fields_table.php
- resources/views/backend/bookings/create.blade.php
- resources/views/backend/bookings/edit.blade.php
- resources/views/backend/bookings/index.blade.php
- resources/views/backend/settings/custom_fields.blade.php
- routes/web.php
- src/Booking.php
- src/BookingCustomField.php
- src/BookingsField.php
- src/BusTravelBaseServiceProvider.php
- src/Http/Controllers/BookingsController.php
- src/Http/Controllers/SettingsController.php
- tests/Feature/BookingsTest.php
- tests/Feature/SettingsTest.php
> feature booking

- database/seeds/DatabaseSeeder.php
- database/seeds/Permission_Roles_UserSeeder.php
- src/BusTravelBaseServiceProvider.php
- src/Seeds/DatabaseSeeder.php
- src/Seeds/PermissionSeeder.php
- tests/Feature/Permissions_Roles_UsersSeederTest.php
Permissions roles users seeder
> permission roles and users seeder

- database/migrations/2019_11_28_081630_add_arrival_time_column_routes_departure_times_table.php
- database/migrations/2019_11_29_091730_create_stopover_routes_table.php
- resources/views/backend/routes/create.blade.php
- resources/views/backend/routes/edit.blade.php
- resources/views/backend/routes/index.blade.php
- resources/views/backend/routes_departures/create.blade.php
- resources/views/backend/routes_departures/edit.blade.php
- resources/views/backend/routes_departures/index.blade.php
- resources/views/backend/settings/custom_fields.blade.php
- src/Http/Controllers/RouteController.php
- src/Http/Controllers/RoutesDepartureTimesController.php
- src/Http/Controllers/SettingsController.php
- src/Route.php
- src/StopoverRoute.php
> route updates

- database/migrations/2019_12_13_081630_add_days_of_week_routes_departure_times_table.php
- database/migrations/2020_01_07_091730_create_stopover_stations_table.php
- resources/views/backend/routes/create.blade.php
- resources/views/backend/routes/edit.blade.php
- resources/views/backend/routes/index.blade.php
- resources/views/backend/routes_departures/edit.blade.php
- src/Http/Controllers/RouteController.php
- src/Http/Controllers/RoutesDepartureTimesController.php
- src/Route.php
- src/RoutesDepartureTime.php
- src/StopoverStation.php
> Routes stopovers

- database/migrations/2020_01_09_081630_create_routes_stopovers_departure_times_table.php
- resources/views/backend/routes/edit.blade.php
- resources/views/backend/routes_departures/create.blade.php
- resources/views/backend/routes_departures/edit.blade.php
- routes/web.php
- src/Http/Controllers/RoutesDepartureTimesController.php
- src/RoutesDepartureTime.php
- src/RoutesStopoversDepartureTime.php
> route times updates

- resources/views/backend/bookings/create.blade.php
- resources/views/backend/bookings/index.blade.php
- resources/views/backend/buses/create.blade.php
- resources/views/backend/buses/edit.blade.php
- resources/views/backend/drivers/create.blade.php
- resources/views/backend/drivers/edit.blade.php
- resources/views/backend/routes/create.blade.php
- resources/views/backend/routes/edit.blade.php
- resources/views/backend/routes_departures/create.blade.php
- resources/views/backend/routes_departures/edit.blade.php
- resources/views/backend/settings/custom_fields.blade.php
- routes/web.php
- src/BookingCustomField.php
- src/Bus.php
- src/BusTravelBaseServiceProvider.php
- src/Driver.php
- src/Http/Controllers/BookingsController.php
- src/Http/Controllers/BusesController.php
- src/Http/Controllers/DriversController.php
- src/Http/Controllers/RouteController.php
- src/Http/Controllers/RoutesDepartureTimesController.php
- src/Http/Controllers/SettingsController.php
- src/Route.php
- src/Traits/OperatorTrait.php
- tests/Feature/RoutesDepartureTimesTest.php
> Operator Trait

- resources/views/backend/routes_departures/create.blade.php
- resources/views/backend/routes_departures/edit.blade.php
> Departure_Arrival time Updates

- database/factories/DriverFactory.php
- database/migrations/2020_03_25_081630_add_user_id_drivers_table.php
- database/migrations/2020_04_03_081630_add_boarded_bookings_table.php
- database/migrations/2020_04_06_081630_create_route_trackings_table.php
- resources/views/backend/bookings/manifest.blade.php
- resources/views/backend/bookings/routemanifest.blade.php
- resources/views/backend/drivers/create.blade.php
- resources/views/backend/drivers/edit.blade.php
- resources/views/backend/users/users/changepassword.blade.php
- routes/web.php
- src/BusTravelBaseServiceProvider.php
- src/Driver.php
- src/Http/Controllers/BookingsController.php
- src/Http/Controllers/DriversController.php
- src/Http/Controllers/UsersController.php
- src/RouteTracking.php
- tests/Feature/DriversTest.php
Change password feature 
Driver manifest
> feature_drivermanifest

- resources/views/frontend/bus_times.blade.php
- src/Http/Controllers/BookingsController.php
> feature_bustimes_updates

- resources/views/backend/bookings/cashier_report.blade.php
- resources/views/backend/reports/cashier_report.blade.php
- resources/views/backend/reports/profitableroutes.blade.php
- resources/views/backend/routes_departures/create.blade.php
- resources/views/backend/routes_departures/edit.blade.php
- routes/web.php
- src/BusTravelBaseServiceProvider.php
- src/Http/Controllers/BookingsController.php
- src/Http/Controllers/OperatorsController.php
- src/Http/Controllers/ReportsController.php
- src/Http/Controllers/RouteController.php
- src/Http/Controllers/RoutesDepartureTimesController.php
- src/Operator.php
- src/RoutesDepartureTime.php
- tests/Feature/OperatorsTest.php
- tests/Feature/RoutesDepartureTimesTest.php
Cashier Report
Performance Report
Routes updates
> feature_route_times_updates

- database/migrations/2020_04_25_091630_add_payment_source_bookings_table.php
- resources/views/backend/reports/bookings.blade.php
- resources/views/backend/reports/cashier_report.blade.php
- resources/views/backend/reports/profitableroutes.blade.php
- resources/views/backend/reports/sales.blade.php
- resources/views/backend/reports/traffic.blade.php
- resources/views/backend/routes_departures/create.blade.php
- resources/views/backend/routes_departures/edit.blade.php
- src/BusTravelBaseServiceProvider.php
- src/Http/Controllers/ReportsController.php
- src/Http/Controllers/RoutesDepartureTimesController.php
- tests/Feature/Permissions_Roles_UsersSeederTest.php
- tests/Feature/RoutesDepartureTimesTest.php
All report changes done 
Route Time  errors fixed
> feature_reports_updates

- src/Http/Controllers/ReportsController.php
> feature_updates_on_reports

- resources/views/backend/bookings/manifest.blade.php
- resources/views/backend/bookings/routemanifest.blade.php
- resources/views/backend/reports/profitableroutes.blade.php
- resources/views/backend/reports/sales.blade.php
- resources/views/backend/reports/traffic.blade.php
- src/BusTravelBaseServiceProvider.php
- src/Http/Controllers/BookingsController.php
- src/RoutesDepartureTime.php
> feature_driver_manifest_update

- resources/views/backend/bookings/routemanifest.blade.php
- resources/views/backend/reports/bookings.blade.php
- resources/views/backend/reports/cashier_report.blade.php
- resources/views/backend/routes/create.blade.php
- resources/views/backend/routes/edit.blade.php
- resources/views/backend/routes_departures/create.blade.php
- resources/views/backend/routes_departures/edit.blade.php
- resources/views/frontend/cart.blade.php
More corrections after merging with Master by Kora.
> More corrections after merging with Master

- database/migrations/2020_05_08_091630_add_inverse_routes_table.php
- resources/views/backend/bookings/routemanifest.blade.php
- resources/views/backend/routes/create.blade.php
- resources/views/backend/routes/edit.blade.php
- src/Http/Controllers/RouteController.php
- src/Http/Controllers/RoutesDepartureTimesController.php
- src/Route.php
> feature-route-inverse

- database/migrations/2020_05_08_091630_add_inverse_routes_table.php
- database/migrations/2020_05_12_091730_create_general_settings_table.php
- resources/views/backend/routes/create.blade.php
- resources/views/backend/routes/edit.blade.php
- resources/views/backend/settings/general_settings.blade.php
- routes/web.php
- src/GeneralSetting.php
- src/Http/Controllers/RouteController.php
- src/Http/Controllers/RoutesDepartureTimesController.php
- src/Http/Controllers/SettingsController.php
> feature_sonacloud_issues

- database/migrations/2019_11_05_071630_create_stations_table.php
- database/migrations/2019_11_05_081630_create_operators_table.php
- database/migrations/2019_11_06_081630_create_buses_table.php
- database/migrations/2019_11_09_081630_create_routes_table.php
- database/migrations/2019_11_10_081630_create_drivers_table.php
- database/migrations/2019_11_11_081630_create_routes_departure_times_table.php
- database/migrations/2019_11_12_081630_create_booking_custom_fields_table.php
- database/migrations/2019_11_12_091630_create_bookings_table.php
- database/migrations/2019_11_12_091730_create_booking_fields_table.php
- database/migrations/2019_11_28_081630_add_arrival_time_column_routes_departure_times_table.php
- database/migrations/2019_11_29_091730_create_stopover_routes_table.php
- database/migrations/2019_12_13_081630_add_days_of_week_routes_departure_times_table.php
- database/migrations/2020_01_07_091730_create_stopover_stations_table.php
- database/migrations/2020_01_09_081630_create_routes_stopovers_departure_times_table.php
- database/migrations/2020_03_12_091730_create_faqs_table.php
- database/migrations/2020_03_25_081630_add_user_id_drivers_table.php
- database/migrations/2020_04_01_091730_create_payment_transactions_table.php
- database/migrations/2020_04_01_091830_create_operator_payment_methods_table.php
- database/migrations/2020_04_02_091830_create_email_templates_table.php
- database/migrations/2020_04_02_091930_create_sms_templates_table.php
- database/migrations/2020_04_02_099562_add_route_type_to_bookings.php
- database/migrations/2020_04_03_081630_add_boarded_bookings_table.php
- database/migrations/2020_04_06_081630_create_route_trackings_table.php
- database/migrations/2020_04_07_091730_create_credit_transactions_table.php
- database/migrations/2020_04_10_081630_add_no_of_tickets_column_payment_transactions_table.php
- database/migrations/2020_04_25_081630_add_payment_source_column_payment_transactions_table.php
- database/migrations/2020_04_25_091630_add_payment_source_bookings_table.php
Feature migrations sonacloud issues
> feature_migrations_sonacloud_issues

- src/BusTravelBaseServiceProvider.php
- src/Http/Controllers/OperatorsController.php
- src/ToastNotification.php
this is in the operators controller only at the moment
> refactor notification

- README.md
- composer.json
- resources/views/backend/layouts/app.blade.php
- resources/views/backend/notifications/edit_email_text_template.blade.php
- resources/views/backend/notifications/email_templates/create.blade.php
- resources/views/backend/notifications/email_templates/edit.blade.php
- resources/views/backend/notifications/email_templates/list.blade.php
- resources/views/backend/notifications/sms_templates/create.blade.php
- resources/views/backend/notifications/sms_templates/edit.blade.php
- resources/views/backend/notifications/sms_templates/list.blade.php
- resources/views/backend/reports/payments/list.blade.php
- routes/web.php
- src/BusTravelBaseServiceProvider.php
- src/EmailTemplate.php
- src/Http/Controllers/ApiController.php
- src/Http/Controllers/PaymentReportsController.php
- src/Http/Controllers/TicketTemplateController.php
some sonar fixes
email templates
sms templates
payment reports
> several additions and fixes

- src/Http/Controllers/BusesController.php
- src/Http/Controllers/DriversController.php
- src/Http/Controllers/FaqsController.php
- src/Http/Controllers/RouteController.php
- src/Http/Controllers/RoutesDepartureTimesController.php
- src/Http/Controllers/SettingsController.php
- src/Http/Controllers/StationsController.php
- src/Http/Controllers/UsersController.php
Feature Controllers Sonacloud Issues
> feature_controller_sonacloud_issues

- resources/views/backend/bookings/manifest.blade.php
- resources/views/backend/bookings/routemanifest.blade.php
- resources/views/backend/bookings/tickets/print.blade.php
- resources/views/backend/drivers/edit.blade.php
- resources/views/backend/drivers/index.blade.php
- resources/views/backend/operators/edit.blade.php
- resources/views/backend/operators/index.blade.php
- resources/views/backend/stations/index.blade.php
- resources/views/frontend/cart.blade.php
- resources/views/frontend/test.blade.php
> feature_sona_bugs

- resources/views/backend/bookings/routemanifest.blade.php
- resources/views/frontend/bus_times.blade.php
- resources/views/frontend/stations.blade.php
> feature_sonarcloud_bugs_updates

- README.md
- composer.lock
- resources/views/backend/routes/create.blade.php
- routes/web.php
- src/Http/Controllers/StationsController.php
Create routes by selecting start, end stations, with ability to have multiple stopovers.
> Build routes from stations

- database/migrations/2020_03_25_081630_add_user_id_drivers_table.php
- database/migrations/2020_04_02_099562_add_route_type_to_bookings.php
- database/migrations/2020_04_03_081630_add_boarded_bookings_table.php
- database/migrations/2020_04_10_081630_add_no_of_tickets_column_payment_transactions_table.php
- database/migrations/2020_04_25_081630_add_payment_source_column_payment_transactions_table.php
- database/migrations/2020_04_25_091630_add_payment_source_bookings_table.php
- database/migrations/2020_05_08_091630_add_inverse_routes_table.php
- database/migrations/2020_05_12_091730_create_general_settings_table.php
- database/migrations/2020_05_21_081632_add_language_column_payment_transactions_table.php
- database/test_migrations/2019_11_14_093428_alter_users_phonenumber_table.php
- database/test_migrations/2019_11_15_093428_alter_users_add_status_table.php
- database/test_migrations/2019_11_16_093428_alter_users_operator_id_table.php
- database/test_migrations/2020_05_18_071630_add_workstation_column_users_table.php
- src/BusTravelBaseServiceProvider.php
- src/Http/Controllers/BookingsController.php
- src/Http/Controllers/BusesController.php
- src/Http/Controllers/DriversController.php
- src/Http/Controllers/OperatorsController.php
- src/Http/Controllers/ReportsController.php
- src/Http/Controllers/SettingsController.php
- src/Http/Controllers/StationsController.php
- src/Http/Controllers/UsersController.php
Feature Sonarcloud Bugs More Updates
> feature_sonarcloud_bugs_more_updates

- database/test_migrations/2019_11_14_093428_alter_users_phonenumber_table.php
- database/test_migrations/2019_11_16_093428_alter_users_operator_id_table.php
- resources/views/backend/bookings/routemanifest.blade.php
- src/BusTravelBaseServiceProvider.php
- src/Http/Controllers/BookingsController.php
- src/Http/Controllers/DriversController.php
- src/Http/Controllers/FaqsController.php
- src/Http/Controllers/OperatorsController.php
- src/Http/Controllers/ReportsController.php
- src/Http/Controllers/RouteController.php
- src/Http/Controllers/RoutesDepartureTimesController.php
- src/Http/Controllers/SettingsController.php
- src/Http/Controllers/UsersController.php
- src/Seeds/PermissionSeeder.php
- tests/Feature/BookingsTest.php
- tests/Feature/BusesTest.php
- tests/Feature/DriversTest.php
- tests/Feature/OperatorsTest.php
- tests/Feature/Permissions_Roles_UsersSeederTest.php
- tests/Feature/RoutesDepartureTimesTest.php
- tests/Feature/RoutesTest.php
- tests/Feature/SettingsTest.php
- tests/Feature/StationsFeatureTest.php
- tests/Feature/UsersTest.php
Feature user Permissions Updates
> feature-user-permissions-changes

- database/factories/BookingFactory.php
- database/migrations/2020_04_25_091630_add_payment_source_bookings_table.php
- resources/views/backend/bookings/create.blade.php
- resources/views/backend/users/users/create.blade.php
- resources/views/backend/users/users/edit.blade.php
- src/Http/Controllers/ReportsController.php
- src/Http/Controllers/UsersController.php
> Feature more permission updates

- resources/views/backend/docs/bookings.blade.php
- resources/views/backend/docs/buses.blade.php
- resources/views/backend/docs/drivers.blade.php
- resources/views/backend/docs/index.blade.php
- resources/views/backend/docs/layout.blade.php
- resources/views/backend/docs/reports.blade.php
- resources/views/backend/docs/routes.blade.php
- resources/views/backend/docs/settings.blade.php
Added "alt" attribute to images
> Alt attribute added to images

- resources/views/backend/bookings/edit.blade.php
- resources/views/backend/reports/payments/list.blade.php
- resources/views/backend/routes_departures/create.blade.php
- resources/views/backend/routes_departures/edit.blade.php
- src/Http/Controllers/BookingsController.php
- src/Http/Controllers/ReportsController.php
- src/Http/Controllers/RouteController.php
- src/Http/Controllers/RoutesDepartureTimesController.php
- src/Http/Requests/CreateBookingRequest.php
- src/Http/Requests/CreateRouteRequest.php
- src/Http/Requests/CreateServicesRequest.php
Feature route services updates
> feature_route_services_updates

- resources/views/backend/reports/payments/list.blade.php
> booking payments updates

- resources/views/frontend/bus_times.blade.php
- resources/views/frontend/cart.blade.php
- resources/views/frontend/checkout.blade.php
- resources/views/frontend/login.blade.php
- resources/views/frontend/register.blade.php
- src/Http/Controllers/FrontendController.php
user registration
editing tickets
> Bugfix trav

- database/migrations/2020_06_11_091425_create_void_tickets_table.php
- resources/views/backend/bookings/create.blade.php
- resources/views/backend/bookings/edit.blade.php
- resources/views/backend/bookings/index.blade.php
- resources/views/backend/reports/bookings.blade.php
- resources/views/backend/reports/cashier_report.blade.php
- routes/web.php
- src/BusTravelBaseServiceProvider.php
- src/Http/Controllers/BookingsController.php
- src/Http/Controllers/ReportsController.php
- src/VoidTicket.php
> feature_cashier_updates

- resources/views/backend/bookings/index.blade.php
- resources/views/backend/bookings/routemanifest.blade.php
- resources/views/backend/buses/index.blade.php
- resources/views/backend/drivers/index.blade.php
- resources/views/backend/routes/edit.blade.php
- resources/views/backend/routes/index.blade.php
- resources/views/backend/routes_departures/create.blade.php
- resources/views/backend/routes_departures/edit.blade.php
- resources/views/backend/stations/index.blade.php
- routes/web.php
- src/Http/Controllers/BookingsController.php
- src/Http/Controllers/BusesController.php
- src/Http/Controllers/DriversController.php
- src/Http/Controllers/RouteController.php
- src/Http/Controllers/RoutesDepartureTimesController.php
- src/Http/Controllers/StationsController.php
> feature_routes_edit_updates

- resources/views/backend/bookings/index.blade.php
- resources/views/backend/bookings/manifest.blade.php
- resources/views/backend/reports/bookings.blade.php
- routes/web.php
- src/Http/Controllers/BookingsController.php
> feature driver manifest

- resources/views/backend/bookings/index.blade.php
- resources/views/backend/bookings/manifest.blade.php
- resources/views/backend/operators/index.blade.php
- resources/views/backend/reports/bookings.blade.php
- resources/views/backend/reports/profitableroutes.blade.php
- resources/views/backend/reports/sales.blade.php
- resources/views/backend/reports/traffic.blade.php
- resources/views/backend/reports/void_bookings.blade.php
- routes/web.php
- src/Http/Controllers/BookingsController.php
- src/Http/Controllers/ReportsController.php
- src/ReportsRoutesPerfomance.php
- src/ReportsRoutesTraffic.php
- src/ReportsSales.php
> Report Updates

- resources/views/backend/reports/cashier_report.blade.php
- resources/views/backend/reports/profitableroutes.blade.php
- src/Http/Controllers/ReportsController.php
- src/ReportsRoutesPerfomance.php
- src/User.php
Route Performance Report Updates
> Report routes Updates

- resources/views/backend/routes_departures/create.blade.php
- resources/views/backend/routes_departures/edit.blade.php
> feature_service_routes_edit

- resources/views/backend/bookings/manifest.blade.php
- resources/views/backend/reports/bookings.blade.php
- src/Http/Controllers/BookingsController.php
- src/ListBookings.php
> edit tickets updates
